#ifndef _ECAT_PDO_CONFIG_H_
#define _ECAT_PDO_CONFIG_H_
#define ECAT_TX_BOOL_COUNT      0
#define ECAT_TX_UINT16_COUNT    128
#define ECAT_RX_BOOL_COUNT      0
#define ECAT_RX_UINT16_COUNT    128
#define ECAT_BOOL_BYTES         (((ECAT_TX_BOOL_COUNT) + 7U) / 8U)
#define ECAT_UINT16_BYTES       ((ECAT_TX_UINT16_COUNT) * 2U)
#define ECAT_PDO_TOTAL_BYTES    (ECAT_BOOL_BYTES + ECAT_UINT16_BYTES)
#endif
